In [430]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [440]:
X = np.loadtxt(open("ex2_x_data.csv", "rb"), delimiter=",")
Y = np.loadtxt(open("ex2_y_data.csv", "rb"), delimiter=",")

In [441]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [442]:
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [448]:
models = np.empty((10, 1), dtype=object)
weights = {
    0:0.05,
    1:0.55,
    2:0.05,
    3:0.05,
    4:0.05,
    5:0.05,
    6:0.05,
    7:0.05,
    8:0.05,
    9:0.05,
}
for i in range(10):
    y_train_i = np.copy(y_train)
    y_train_i[y_train != i] = 0
    y_train_i[y_train == i] = 1
    models[i, 0] = LogisticRegression(fit_intercept=True, max_iter=100, n_jobs=-1, C=0.005, penalty='l2', class_weight=weights).fit(X_train, y_train_i)

In [449]:
y_pred = np.zeros((y_test.size, 10))
for i in range(10):
    y = models[i, 0].predict_proba(X_test)
    y_pred[:, i] = y[:, -1]
test_class_pred = np.zeros((y_test.size))
for i in range (y_test.size):
    test_class_pred[i] = np.argmax(y_pred[i, :])

In [450]:
y_pred = np.zeros((y_train.size, 10))
for i in range(10):
    y = models[i, 0].predict_proba(X_train)
    y_pred[:, i] = y[:, -1]
train_class_pred = np.zeros((y_train.size))
for i in range (y_train.size):
    train_class_pred[i] = np.argmax(y_pred[i, :])

In [451]:
testconMat = confusion_matrix(y_test, test_class_pred)
trainconMat = confusion_matrix(y_train, train_class_pred)
print(testconMat)
print(trainconMat)

[[53  0  0  0  0  1  1  0  0  0]
 [ 0 35  9  0  0  0  0  0  7  4]
 [ 0  3 45  2  0  0  0  0  2  0]
 [ 0  0  3 48  0  0  0  1  2  2]
 [ 0  4  0  0 54  1  3  2  0  0]
 [ 0  1  1  1  1 54  1  1  0 13]
 [ 0  0  0  0  1  0 55  0  1  0]
 [ 0  0  1  0  0  0  0 60  1  0]
 [ 0  5  1  1  0  1  3  1 38  2]
 [ 0  1  2  6  1  1  0  1  4 52]]
[[122   0   0   0   1   0   0   0   0   0]
 [  0 105   4   0   0   2   3   2   3   8]
 [  1   5 112   2   0   0   0   1   4   0]
 [  0   1   1 112   0   3   1   2   2   5]
 [  0   6   0   0 104   1   0   3   3   0]
 [  0   1   0   5   1  88   0   2   3   9]
 [  1   4   0   0   0   0 117   0   2   0]
 [  0   0   0   0   1   1   0 114   1   0]
 [  0  11   1   6   1   2   1   3  95   2]
 [  0   3   0  14   1   2   0   5   2  85]]


In [452]:
precision = np.zeros((10))
recall = np.zeros((10))
acc = 0
for i in range(10):
    precision[i] = testconMat[i, i] / np.sum(testconMat[:, i])
    recall[i] = testconMat[i, i] / np.sum(testconMat[i, :])
    acc += testconMat[i, i]
print("\ni precision: \n", precision)
print("\ni recall: \n", recall)
print("\ntotal precision: ", np.mean(precision))
print("total recall: ", np.mean(recall))
print("acc: ", acc / np.sum(np.sum(testconMat)))


i precision: 
 [1.         0.71428571 0.72580645 0.82758621 0.94736842 0.93103448
 0.87301587 0.90909091 0.69090909 0.71232877]

i recall: 
 [0.96363636 0.63636364 0.86538462 0.85714286 0.84375    0.73972603
 0.96491228 0.96774194 0.73076923 0.76470588]

total precision:  0.8331425916745582
total recall:  0.833413282923253
acc:  0.8316498316498316


In [453]:
precision = np.zeros((10))
recall = np.zeros((10))
acc = 0
for i in range(10):
    precision[i] = trainconMat[i, i] / np.sum(trainconMat[:, i])
    recall[i] = trainconMat[i, i] / np.sum(trainconMat[i, :])
    acc += trainconMat[i, i]
print("\ni precision: \n", precision)
print("\ni recall: \n", recall)
print("\ntotal precision: ", np.mean(precision))
print("total recall: ", np.mean(recall))
print("acc: ", acc / np.sum(np.sum(trainconMat)))


i precision: 
 [0.98387097 0.77205882 0.94915254 0.8057554  0.95412844 0.88888889
 0.95901639 0.86363636 0.82608696 0.77981651]

i recall: 
 [0.99186992 0.82677165 0.896      0.88188976 0.88888889 0.80733945
 0.94354839 0.97435897 0.77868852 0.75892857]

total precision:  0.8782411285945736
total recall:  0.8748284131926679
acc:  0.8761429758935994
